### ISSUE TITLE
CI error: error CS0103: The name 'SyncedEnforcer' does not exist in the current context

### ISSUE THREAD

**Issue by hsluoyz** [casbin-net/casbin-aspnetcore#55] opened 2022-12-07 08:01 UTC
https://github.com/casbin-net/casbin-aspnetcore/actions/runs/3630850164/jobs/6124702645

![image](https://user-images.githubusercontent.com/3787410/206121514-3b821682-c56f-47fe-8f1c-3a81e334980d.png)

**Comment by ZhengLin-Li** [comment] 2023-01-06 02:53
Actually, there is no `SyncedEnforcer` class in this project. I have searched the keyword `SyncedEnforcer` and let my IDE find them in files, and it turned out the keyword `SyncedEnforcer` only appears three times.

So, I believe this issue may be caused by some copy-paste problems. I will fix it in my next PR.

**Comment by sagilio** [comment] 2023-01-06 06:55
The reason is dependency package version be deleted.
![image](https://user-images.githubusercontent.com/42855245/210946980-e809a3bc-e9e0-4965-80a5-645ca4f5304f.png)

**Comment by ZhengLin-Li** [comment] 2023-01-06 08:46
> The reason is dependency package version be deleted. ![image](https://user-images.githubusercontent.com/42855245/210946980-e809a3bc-e9e0-4965-80a5-645ca4f5304f.png)

@sagilio So, how shall we solve this? you could request change in my PR here https://github.com/casbin-net/casbin-aspnetcore/pull/57.

**Comment by sagilio** [comment] 2023-03-20 15:53
Fixed by https://github.com/casbin-net/casbin-aspnetcore/commit/85ad73cca19ae59ff6fb94e2e1e67510bfbd4975

**Closed by sagilio** 2023-03-20 15:53 UTC
Labels: bug
